language: ruby
before_install:
  - gem update --system
  - gem update bundler -v 1.17.3
  - gem cleanup bundler
install: "bundle install --jobs 8"
rvm:
  - 2.4.6
  - 2.5.5
  - ruby-head
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
matrix:
  exclude:
    - rvm: ruby-head
      gemfile: gemfiles/rails42.gemfile
  fast_finish: true
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec
