language: ruby
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
install: "bundle install --jobs 8"
rvm:
  - 1.9.3
  - 2.2.10
  - 2.4.5
  - 2.5.3
  - ruby-head
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails50.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails51.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails52.gemfile
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec
